### ISSUE TITLE
change tei:note to tei:desc in Taxonomy

### ISSUE THREAD

**Issue by dlschwartz** [wlpotter/csv-to-srophe#48]
@wlpotter I've been typing up notes for Winona's work on the html and started comparing the data in column AF to what we have in the other modules. It looks like the rough equivalent in persons is tei:note while the rough equivalent in places is tei:desc. I'm not sure if the updates we need to make with persons will shift to tei:desc, but now that I look more closely I do believe that tei:desc is better in the Taxonomy. Can you please change the transform of column AF to tei:desc. I don't think we need to add a @type attribute as tei:desc pretty well captures the meaning. Let's keep the xml:lang though. Thanks Will!

**Comment by wlpotter** [comment]
@dlschwartz I will make change tei:note to tei:desc in the transform for subjects.

For some context on why we have tei:note in persons and tei:desc in places, this is because [tei:person](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-person.html) cannot contain a tei:desc, but [tei:place](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-place.html) can. (It's not clear to me why that's the case).

**Comment by wlpotter** [comment]
The data [here](https://github.com/wlpotter/csv-to-srophe/tree/main/out/subjects/2022-03-10) is updated based on the change to how column AF is output.

**Comment by dlschwartz** [comment]
@wlpotter Thank you! And thanks for the reminder about what's allowed in tei:person. I recall that now. This looks great. I'll delete the current taxonomy files in srophe and add these. I'll post an issue for Winona's work on the html as well. Thanks!
